/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asignacion.vista;

/**
 *
 * @author Diana
 */
public class ProcesoMenus extends javax.swing.JFrame {

    /**
     * Creates new form ProcesoMenus
     */
    public ProcesoMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBoletaCursosAsignacion = new javax.swing.JButton();
        btnAsignacionCursos = new javax.swing.JButton();
        btnPensum = new javax.swing.JButton();
        btnCertificacionCursoso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListadoAlumnoPorCurso = new javax.swing.JButton();
        btnListadoAlumnoCursoCatedratico1 = new javax.swing.JButton();
        btnCursosHabilitadosCatedratico1 = new javax.swing.JButton();
        btnCursosHabilitadosAlumno1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnListadoAlumnoPorSecccion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        btnBoletaCursosAsignacion.setText("Boleta Asignacion Cursos");
        btnBoletaCursosAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletaCursosAsignacionActionPerformed(evt);
            }
        });

        btnAsignacionCursos.setText("Asignacion Cursos");
        btnAsignacionCursos.setPreferredSize(new java.awt.Dimension(129, 23));
        btnAsignacionCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionCursosActionPerformed(evt);
            }
        });

        btnPensum.setText("Pensum");
        btnPensum.setPreferredSize(new java.awt.Dimension(129, 23));
        btnPensum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPensumActionPerformed(evt);
            }
        });

        btnCertificacionCursoso.setText("Certificacion Cursos");
        btnCertificacionCursoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificacionCursosoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MENU DE PROCESOS");

        btnListadoAlumnoPorCurso.setText("Listado Alumnos Por Curso");
        btnListadoAlumnoPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoAlumnoPorCursoActionPerformed(evt);
            }
        });

        btnListadoAlumnoCursoCatedratico1.setText("Listado Alumno Curso Catedratico");
        btnListadoAlumnoCursoCatedratico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoAlumnoCursoCatedratico1ActionPerformed(evt);
            }
        });

        btnCursosHabilitadosCatedratico1.setText("Curso Habilitados Catedraticos");
        btnCursosHabilitadosCatedratico1.setPreferredSize(new java.awt.Dimension(129, 23));
        btnCursosHabilitadosCatedratico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosHabilitadosCatedratico1ActionPerformed(evt);
            }
        });

        btnCursosHabilitadosAlumno1.setText("Cursos Habilitados Alumno");
        btnCursosHabilitadosAlumno1.setPreferredSize(new java.awt.Dimension(129, 23));
        btnCursosHabilitadosAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosHabilitadosAlumno1ActionPerformed(evt);
            }
        });

        jButton8.setText("Listado Alumnos Por Carrera");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnListadoAlumnoPorSecccion.setText("Listado Alumnos Por Seccion");
        btnListadoAlumnoPorSecccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoAlumnoPorSecccionActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListadoAlumnoCursoCatedratico1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnCertificacionCursoso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                        .addComponent(btnPensum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBoletaCursosAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAsignacionCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnCursosHabilitadosAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnListadoAlumnoPorSecccion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCursosHabilitadosCatedratico1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                        .addComponent(btnListadoAlumnoPorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBoletaCursosAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsignacionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(btnPensum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCursosHabilitadosCatedratico1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListadoAlumnoPorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListadoAlumnoPorSecccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCertificacionCursoso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCursosHabilitadosAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListadoAlumnoCursoCatedratico1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoletaCursosAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaCursosAsignacionActionPerformed
        // TODO add your handling code here:
        AsignacionDeCursos frm = new AsignacionDeCursos();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBoletaCursosAsignacionActionPerformed

    private void btnAsignacionCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionCursosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAsignacionCursosActionPerformed

    private void btnCursosHabilitadosAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosHabilitadosAlumno1ActionPerformed
        // TODO add your handling code here:
        CertificacionCursos frm = new CertificacionCursos();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCursosHabilitadosAlumno1ActionPerformed

    private void btnPensumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPensumActionPerformed
        // TODO add your handling code here:
        Pensum frm = new Pensum();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPensumActionPerformed

    private void btnCertificacionCursosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificacionCursosoActionPerformed
        // TODO add your handling code here:
        CertificacionCursos frm = new CertificacionCursos();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCertificacionCursosoActionPerformed

    private void btnCursosHabilitadosCatedratico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosHabilitadosCatedratico1ActionPerformed
        // TODO add your handling code here:
        CursosCatedraticos frm = new CursosCatedraticos();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCursosHabilitadosCatedratico1ActionPerformed

    private void btnListadoAlumnoPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoAlumnoPorCursoActionPerformed
        // TODO add your handling code here:
        Listadoalumnoscurso frm = new Listadoalumnoscurso();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListadoAlumnoPorCursoActionPerformed

    private void btnListadoAlumnoPorSecccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoAlumnoPorSecccionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnListadoAlumnoPorSecccionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        Listadoalumnoscarreraporcarrera frm = new Listadoalumnoscarreraporcarrera();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnListadoAlumnoCursoCatedratico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoAlumnoCursoCatedratico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListadoAlumnoCursoCatedratico1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MDISistema frm = new MDISistema();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesoMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesoMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesoMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesoMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesoMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignacionCursos;
    private javax.swing.JButton btnBoletaCursosAsignacion;
    private javax.swing.JButton btnCertificacionCursoso;
    private javax.swing.JButton btnCursosHabilitadosAlumno1;
    private javax.swing.JButton btnCursosHabilitadosCatedratico1;
    private javax.swing.JButton btnListadoAlumnoCursoCatedratico1;
    private javax.swing.JButton btnListadoAlumnoPorCurso;
    private javax.swing.JButton btnListadoAlumnoPorSecccion;
    private javax.swing.JButton btnPensum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
